version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myHEJProject/wepin-api # 인스턴스에서 파일이 저장될 위치
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/myHEJProject/wepin-api
    #    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: wepin-api-deploy.sh    # locaiton 기준 => project root 디렉토리
      timeout: 60
      runas: root
